module.exports = [
  { suit: "hammer", ability: "STR", name: "The Paladin", alignment: "LG" },
  { suit: "hammer", ability: "STR", name: "The Keep", alignment: "NG" },
  { suit: "hammer", ability: "STR", name: "The Big Sky", alignment: "CG" },
  { suit: "hammer", ability: "STR", name: "The Forge", alignment: "LN" },
  { suit: "hammer", ability: "STR", name: "The Bear", alignment: "N" },
  { suit: "hammer", ability: "STR", name: "The Uprising", alignment: "CN" },
  { suit: "hammer", ability: "STR", name: "The Fiend", alignment: "LE" },
  { suit: "hammer", ability: "STR", name: "The Beating", alignment: "NE" },
  { suit: "hammer", ability: "STR", name: "The Cyclone", alignment: "CE" },

  { suit: "key", ability: "DEX", name: "The Dance", alignment: "LG" },
  { suit: "key", ability: "DEX", name: "The Cricket", alignment: "NG" },
  { suit: "key", ability: "DEX", name: "The Juggler", alignment: "CG" },
  { suit: "key", ability: "DEX", name: "The Locksmith", alignment: "LN" },
  { suit: "key", ability: "DEX", name: "The Peacock", alignment: "N" },
  { suit: "key", ability: "DEX", name: "The Rabbit Prince", alignment: "CN" },
  { suit: "key", ability: "DEX", name: "The Avalanche", alignment: "LE" },
  { suit: "key", ability: "DEX", name: "The Crows", alignment: "NE" },
  { suit: "key", ability: "DEX", name: "The Demon's Lantern", alignment: "CE" },

  { suit: "shield", ability: "CON", name: "The Trumpet", alignment: "LG" },
  { suit: "shield", ability: "CON", name: "The Survivor", alignment: "NG" },
  { suit: "shield", ability: "CON", name: "The Desert", alignment: "CG" },
  { suit: "shield", ability: "CON", name: "The Brass Dwarf", alignment: "LN" },
  { suit: "shield", ability: "CON", name: "The Teamster", alignment: "N" },
  { suit: "shield", ability: "CON", name: "The Mountain Man", alignment: "CN" },
  {
    suit: "shield",
    ability: "CON",
    name: "The Tangled Briar",
    alignment: "LE"
  },
  { suit: "shield", ability: "CON", name: "The Sickness", alignment: "NE" },
  { suit: "shield", ability: "CON", name: "The Waxworks", alignment: "CE" },

  { suit: "book", ability: "INT", name: "The Hidden Truth", alignment: "LG" },
  { suit: "book", ability: "INT", name: "The Wanderer", alignment: "NG" },
  { suit: "book", ability: "INT", name: "The Joke", alignment: "CG" },
  { suit: "book", ability: "INT", name: "The Inquisitor", alignment: "LN" },
  { suit: "book", ability: "INT", name: "The Foreign Trader", alignment: "N" },
  { suit: "book", ability: "INT", name: "The Vision", alignment: "CN" },
  { suit: "book", ability: "INT", name: "The Rakshasa", alignment: "LE" },
  { suit: "book", ability: "INT", name: "The Idiot", alignment: "NE" },
  { suit: "book", ability: "INT", name: "The Snakebite", alignment: "CE" },

  { suit: "star", ability: "WIS", name: "The Winged Serpent", alignment: "LG" },
  { suit: "star", ability: "WIS", name: "The Widwife", alignment: "NG" },
  { suit: "star", ability: "WIS", name: "The Publican", alignment: "CG" },
  { suit: "star", ability: "WIS", name: "The Queen Mother", alignment: "LN" },
  { suit: "star", ability: "WIS", name: "The Owl", alignment: "N" },
  { suit: "star", ability: "WIS", name: "The Carnival", alignment: "CN" },
  { suit: "star", ability: "WIS", name: "The Eclipse", alignment: "LE" },
  { suit: "star", ability: "WIS", name: "The Mute Hag", alignment: "NE" },
  { suit: "star", ability: "WIS", name: "The Lost", alignment: "CE" },

  { suit: "crown", ability: "CHA", name: "The Empty Throne", alignment: "LG" },
  { suit: "crown", ability: "CHA", name: "The Theater", alignment: "NG" },
  { suit: "crown", ability: "CHA", name: "The Unicorn", alignment: "CG" },
  { suit: "crown", ability: "CHA", name: "The Marriage", alignment: "LN" },
  { suit: "crown", ability: "CHA", name: "The Twin", alignment: "N" },
  { suit: "crown", ability: "CHA", name: "The Courtesan", alignment: "CN" },
  { suit: "crown", ability: "CHA", name: "The Tyrant", alignment: "LE" },
  { suit: "crown", ability: "CHA", name: "The Betrayal", alignment: "NE" },
  { suit: "crown", ability: "CHA", name: "The Liar", alignment: "CE" }
];
